# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 46216f8f8fc2ad8bbb28f304290a947e546dcc56abc2568095704c0804ec282b3de81862ed2350f55c42444f9ec8798fc6ed2d3abb5e66a3ca375025f1f36e69

test:
  secret_key_base: f08747c3c5632293a623162b442fd9fc60deecbc5455c4cbc287485b9e76168ecced866cc4f6c9155b21fc13876ee0cf50c4cdefe2bb546a895f62c92a4869f4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
